# Generated by Django 5.0.3 on 2024-03-21 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cel', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=100)),
                ('cuit', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.BigIntegerField()),
                ('marca', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ventas.cliente')),
                ('producto_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ventas.producto')),
            ],
        ),
    ]
