# Generated by Django 5.0.3 on 2024-03-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ventas', '0002_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_cel',
            field=models.IntegerField(),
        ),
    ]
