# Generated by Django 5.0.3 on 2024-03-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ventas', '0003_alter_cliente_numero_cel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_cel',
            field=models.CharField(max_length=100),
        ),
    ]
