# Generated by Django 5.0.3 on 2024-03-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ventas', '0004_alter_cliente_numero_cel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='producto_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='subtotal',
        ),
    ]
