# Generated by Django 5.0.3 on 2024-03-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ventas', '0006_rename_total_pedido_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_cliente',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
