# Generated by Django 5.0.2 on 2024-02-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('Product_descripcion', models.TextField()),
                ('Activo', models.BooleanField()),
                ('Precio', models.FloatField()),
            ],
        ),
    ]
