# Generated by Django 5.0.2 on 2024-03-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Felfort_retail', '0002_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='id_prodcuto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
