# Generated by Django 5.0.2 on 2024-03-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Felfort_retail', '0003_productos_id_prodcuto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='id_prodcuto',
            new_name='id_producto',
        ),
    ]
