# Generated by Django 5.0.2 on 2024-03-06 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Felfort_retail', '0005_pedido_pedidoproducto_pedido_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='Activo',
        ),
    ]
